/* MODULO ESTADO */
ALTER TABLE FIDE_ESTADO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO USUARIO */
ALTER TABLE FIDE_TIPO_USUARIO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_USUARIO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_CORREO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_TELEFONO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO DIRECCION */
ALTER TABLE FIDE_PAIS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_PROVINCIA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_CANTON_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_DISTRITO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_DIRECCION_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO AUTENTICACION */
ALTER TABLE FIDE_CUENTA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_TIPO_OTP_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_CODIGO_OTP_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_REFRESH_TOKEN_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO PRODUCTOS */
ALTER TABLE FIDE_CATEGORIA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_PRODUCTO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO INVENTARIO */
ALTER TABLE FIDE_INVENTARIO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_TIPO_MOVIMIENTO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_MOVIMIENTO_INVENTARIO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO TIENDA */
ALTER TABLE FIDE_VENTA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_VENTA_PRODUCTO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO EVENTOS */
ALTER TABLE FIDE_EVENTO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_TIPO_CONTENIDO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_CONTENIDO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO TICKETS */
ALTER TABLE FIDE_TIPO_TICKET_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_EVENTO_TICKET ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_TICKET_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO FACTURACION */
ALTER TABLE FIDE_MONEDA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_FACTURA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_VENTA_FACTURA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_TICKET_FACTURA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_PAGO_PAYPAL_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO MUSICA */
ALTER TABLE FIDE_SEASON_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_SEASON_SET_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO REDES SOCIALES */
ALTER TABLE FIDE_RED_SOCIAL_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_CUENTA_RED_SOCIAL_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

/* MODULO CARRITO DE COMPRAS */
ALTER TABLE FIDE_CARRITO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_CARRITO_ITEM_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
/


