/* MODULO ESTADO */
CREATE TABLE FIDE_ESTADO_TB(
    ID_ESTADO       NUMBER,
    NOMBRE_ESTADO   VARCHAR(100),

    CONSTRAINT FIDE_ESTADO_PK_TB PRIMARY KEY (ID_ESTADO)
);
/

/*  MODULO USUARIO */
CREATE TABLE FIDE_TIPO_USUARIO_TB(
    ID_TIPO_USUARIO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_TIPO_USUARIO_PK_ID_TIPO_USUARIO PRIMARY KEY(ID_TIPO_USUARIO),
    CONSTRAINT FIDE_TIPO_USUARIO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO DE DIRECCION */
CREATE TABLE FIDE_PAIS_TB(
    ID_PAIS NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_PAIS_PK_ID_PAIS PRIMARY KEY(ID_PAIS),
    CONSTRAINT FIDE_PAIS_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_PROVINCIA_TB(
    ID_PROVINCIA NUMBER,
    NOMBRE VARCHAR2(100),
    ID_PAIS NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_PROVINCIA_PK_ID_PROVINCIA PRIMARY KEY(ID_PROVINCIA),
    CONSTRAINT FIDE_PROVINCIA_FK_ID_PAIS FOREIGN KEY(ID_PAIS)
        REFERENCES FIDE_PAIS_TB(ID_PAIS),
    CONSTRAINT FIDE_PROVINCIA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CANTON_TB(
    ID_CANTON NUMBER,
    NOMBRE VARCHAR2(100),
    ID_PROVINCIA NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CANTON_PK_ID_CANTON PRIMARY KEY(ID_CANTON),
    CONSTRAINT FIDE_CANTON_FK_ID_PROVINCIA FOREIGN KEY(ID_PROVINCIA)
        REFERENCES FIDE_PROVINCIA_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_CANTON_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DISTRITO_TB(
    ID_DISTRITO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_CANTON NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_DISTRITO_PK_ID_DISTRITO PRIMARY KEY(ID_DISTRITO),
    CONSTRAINT FIDE_DISTRITO_FK_ID_CANTON FOREIGN KEY(ID_CANTON)
        REFERENCES FIDE_CANTON_TB(ID_CANTON),
    CONSTRAINT FIDE_DISTRITO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DIRECCION_TB(
    ID_DIRECCION NUMBER,
    ID_DISTRITO NUMBER,
    CALLE VARCHAR2(100),
    NUMERO VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_DIRECCION_PK_ID_DIRECCION PRIMARY KEY(ID_DIRECCION),
    CONSTRAINT FIDE_DIRECCION_FK_ID_DISTRITO FOREIGN KEY(ID_DISTRITO)
        REFERENCES FIDE_DISTRITO_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCION_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_USUARIO_TB(
    IDENTIFICACION NUMBER,
    NOMBRE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    ID_DIRECCION NUMBER,
    ID_TIPO_USUARIO NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_USUARIO_PK_IDENTIFICACION PRIMARY KEY(IDENTIFICACION),
    CONSTRAINT FIDE_USUARIO_FK_ID_DIRECCION FOREIGN KEY(ID_DIRECCION)
        REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION),
    CONSTRAINT FIDE_USUARIO_FK_ID_TIPO_USUARIO FOREIGN KEY(ID_TIPO_USUARIO)
        REFERENCES FIDE_TIPO_USUARIO_TB(ID_TIPO_USUARIO),
    CONSTRAINT FIDE_USUARIO_FK__ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CORREO_TB(
    IDENTIFICACION NUMBER,
    CORREO VARCHAR2(100)
    CONSTRAINT CORREO_UNIQUE UNIQUE
    CONSTRAINT CORREO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CORREO_PK_IDENTIFICACION_CORREO PRIMARY KEY(IDENTIFICACION, CORREO),
    CONSTRAINT FIDE_CORREO_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_CORREO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TELEFONO_TB(
    IDENTIFICACION NUMBER,
    TELEFONO VARCHAR2(100)
    CONSTRAINT TELEFONO_UNIQUE UNIQUE
    CONSTRAINT TELEFONO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_TELEFONO_PK_IDENTIFICACION_TELEFONO PRIMARY KEY(IDENTIFICACION, TELEFONO),
    CONSTRAINT FIDE_TELEFONO_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_TELEFONO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO AUTENTICACION */
CREATE TABLE FIDE_CUENTA_TB(
    ID_CUENTA NUMBER,
    IDENTIFICACION NUMBER,
    USUARIO VARCHAR2(100),
    PASSWORD_HASH VARCHAR2(255)
    CONSTRAINT PASSWORD_HASH_NOT_NULL NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CUENTA_PK_ID_CUENTA PRIMARY KEY(ID_CUENTA),
    CONSTRAINT FIDE_CUENTA_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_CUENTA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_OTP_TB(
    ID_TIPO_OTP NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_TIPO_OTP_PK_ID_TIPO_OTP PRIMARY KEY(ID_TIPO_OTP),
    CONSTRAINT FIDE_TIPO_OTP_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CODIGO_OTP_TB(
    ID_CODIGO_OTP NUMBER,
    ID_CUENTA NUMBER,
    ID_TIPO_OTP NUMBER,
    CODIGO_HASH VARCHAR2(200),
    FECHA_EXPIRACION DATE,
    FECHA_USO DATE,
    INTENTOS NUMBER,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CODIGO_OTP_PK_ID_CODIGO_OTP PRIMARY KEY(ID_CODIGO_OTP),
    CONSTRAINT FIDE_CODIGO_OTP_FK_ID_CUENTA FOREIGN KEY(ID_CUENTA)
        REFERENCES FIDE_CUENTA_TB(ID_CUENTA),
    CONSTRAINT FIDE_CODIGO_OTP_FK_ID_TIPO_OTP FOREIGN KEY(ID_TIPO_OTP)
        REFERENCES FIDE_TIPO_OTP_TB(ID_TIPO_OTP),
    CONSTRAINT FIDE_CODIGO_OTP_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_REFRESH_TOKEN_TB(
    ID_REFRESH_TOKEN NUMBER,
    ID_CUENTA NUMBER,
    TOKEN_HASH VARCHAR2(500),
    JTI VARCHAR2(100),
    IP_ADDRESS VARCHAR2(100),
    USER_AGENT VARCHAR2(300),
    FECHA_EXPIRACION DATE,
    FECHA_REVOCACION DATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_REFRESH_TOKEN_PK_ID_REFRESH_TOKEN PRIMARY KEY(ID_REFRESH_TOKEN),
    CONSTRAINT FIDE_REFRESH_TOKEN_FK_ID_CUENTA FOREIGN KEY(ID_CUENTA)
        REFERENCES FIDE_CUENTA_TB(ID_CUENTA),
    CONSTRAINT FIDE_REFRESH_TOKEN_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO PRODUCTOS */
CREATE TABLE FIDE_CATEGORIA_TB(
    ID_CATEGORIA NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CATEGORIA_PK_ID_CATEGORIA PRIMARY KEY(ID_CATEGORIA),
    CONSTRAINT FIDE_CATEGORIA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_PRODUCTO_TB(
    ID_PRODUCTO NUMBER,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(500),
    PRECIO NUMBER,
    ID_CATEGORIA NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_PRODUCTO_PK_ID_PRODUCTO PRIMARY KEY(ID_PRODUCTO),
    CONSTRAINT FIDE_PRODUCTO_FK_ID_CATEGORIA FOREIGN KEY(ID_CATEGORIA)
        REFERENCES FIDE_CATEGORIA_TB(ID_CATEGORIA),
    CONSTRAINT FIDE_PRODUCTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO INVENTARIO */
CREATE TABLE FIDE_INVENTARIO_TB(
    ID_INVENTARIO NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_INVENTARIO_PK_ID_INVENTARIO PRIMARY KEY(ID_INVENTARIO),
    CONSTRAINT FIDE_INVENTARIO_FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FIDE_INVENTARIO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_MOVIMIENTO_TB(
    ID_TIPO_MOVIMIENTO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_TIPO_MOVIMIENTO_PK_ID_TIPO_MOVIMIENTO PRIMARY KEY(ID_TIPO_MOVIMIENTO),
    CONSTRAINT FIDE_TIPO_MOVIMIENTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_MOVIMIENTO_INVENTARIO_TB(
    ID_MOVIMIENTO NUMBER,
    ID_PRODUCTO NUMBER,
    ID_TIPO_MOVIMIENTO NUMBER,
    CANTIDAD NUMBER,
    FECHA_MOVIMIENTO DATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_PK_ID_MOVIMIENTO PRIMARY KEY(ID_MOVIMIENTO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_FK_ID_TIPO_MOVIMIENTO FOREIGN KEY(ID_TIPO_MOVIMIENTO)
        REFERENCES FIDE_TIPO_MOVIMIENTO_TB(ID_TIPO_MOVIMIENTO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO TIENDA */
CREATE TABLE FIDE_VENTA_TB(
    ID_VENTA NUMBER,
    ID_CUENTA NUMBER,
    TOTAL_VENTA NUMBER(8,2),
    FECHA_VENTA DATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_VENTA_PK_ID_VENTA PRIMARY KEY(ID_VENTA),
    CONSTRAINT FIDE_VENTA_FK_ID_CUENTA FOREIGN KEY(ID_CUENTA)
        REFERENCES FIDE_CUENTA_TB(ID_CUENTA),
    CONSTRAINT FIDE_VENTA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_VENTA_PRODUCTO_TB(
    ID_VENTA NUMBER,
    ID_PRODUCTO NUMBER,
    ID_TIPO_MOVIMIENTO NUMBER,
    CANTIDAD NUMBER,
    TOTAL NUMBER(8,2),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_VENTA_PRODUCTO_PK_ID_VENTA_ID_PRODUCTO PRIMARY KEY(ID_VENTA, ID_PRODUCTO),
    CONSTRAINT FIDE_VENTA_PRODUCTO_FK_ID_VENTA FOREIGN KEY(ID_VENTA)
        REFERENCES FIDE_VENTA_TB(ID_VENTA),
    CONSTRAINT FIDE_VENTA_PRODUCTO_FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FIDE_VENTA_PRODUCTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO EVENTOS */
CREATE TABLE FIDE_EVENTO_TB(
    ID_EVENTO NUMBER,
    TITULO VARCHAR2(150),
    DESCRIPCION VARCHAR2(500),
    FECHA_EVENTO DATE,
    ID_DIRECCION NUMBER,
    FLYER_URL VARCHAR2(300),
    PRECIO NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_EVENTO_PK PRIMARY KEY(ID_EVENTO),
    CONSTRAINT FIDE_EVENTO_FK_DIRECCION
        FOREIGN KEY(ID_DIRECCION)
        REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION),
    CONSTRAINT FIDE_EVENTO_FK_ESTADO
        FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_CONTENIDO_TB(
    ID_TIPO_CONTENIDO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_TIPO_CONTENIDO_PK_ID_TIPO_CONTENIDO PRIMARY KEY(ID_TIPO_CONTENIDO),
    CONSTRAINT FIDE_TIPO_CONTENIDO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CONTENIDO_TB(
    ID_CONTENIDO NUMBER,
    ID_EVENTO NUMBER,
    ID_TIPO_CONTENIDO NUMBER,
    TITULO VARCHAR2(150),
    DESCRIPCION VARCHAR2(500),
    URL VARCHAR2(300),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CONTENIDO_PK_ID_CONTENIDO PRIMARY KEY(ID_CONTENIDO),
    CONSTRAINT FIDE_CONTENIDO_FK_ID_EVENTO FOREIGN KEY(ID_EVENTO)
        REFERENCES FIDE_EVENTO_TB(ID_EVENTO),
    CONSTRAINT FIDE_CONTENIDO_FK_ID_TIPO_CONTENIDO FOREIGN KEY(ID_TIPO_CONTENIDO)
        REFERENCES FIDE_TIPO_CONTENIDO_TB(ID_TIPO_CONTENIDO),
    CONSTRAINT FIDE_CONTENIDO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO TICKETS */
CREATE TABLE FIDE_TIPO_TICKET_TB(
    ID_TIPO_TICKET NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_TIPO_TICKET_PK PRIMARY KEY(ID_TIPO_TICKET),
    CONSTRAINT FIDE_TIPO_TICKET_FK_ESTADO
        FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_EVENTO_TICKET(
    ID_EVENTO_TICKET NUMBER,
    ID_EVENTO NUMBER,
    ID_TIPO_TICKET NUMBER,
    PRECIO NUMBER(8,2),
    CUPOS_TOTALES NUMBER,
    CUPOS_DISPONIBLES NUMBER,
    CUPOS_VENDIDOS NUMBER,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_EVENTO_TICKET_PK PRIMARY KEY(ID_EVENTO_TICKET),
    CONSTRAINT FIDE_EVENTO_TICKET_FK_EVENTO FOREIGN KEY(ID_EVENTO)
        REFERENCES FIDE_EVENTO_TB(ID_EVENTO),
    CONSTRAINT FIDE_EVENTO_TICKET_FK_TIPO FOREIGN KEY(ID_TIPO_TICKET)
        REFERENCES FIDE_TIPO_TICKET_TB(ID_TIPO_TICKET),
    CONSTRAINT FIDE_EVENTO_TICKET_FK_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TICKET_TB(
    ID_TICKET NUMBER,
    ID_EVENTO_TICKET NUMBER,
    ID_CUENTA NUMBER,
    CODIGO_QR VARCHAR2(200),
    FECHA_GENERACION DATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_TICKET_PK PRIMARY KEY(ID_TICKET),
    CONSTRAINT FIDE_TICKET_FK_EVENTO_TICKET FOREIGN KEY(ID_EVENTO_TICKET)
        REFERENCES FIDE_EVENTO_TICKET(ID_EVENTO_TICKET),
    CONSTRAINT FIDE_TICKET_FK_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO FACTURACION */
CREATE TABLE FIDE_MONEDA_TB(
    ID_MONEDA NUMBER,
    NOMBRE VARCHAR2(100),
    SIMBOLO VARCHAR2(10),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_MONEDA_PK_ID_MONEDA PRIMARY KEY(ID_MONEDA),
    CONSTRAINT FIDE_MONEDA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_FACTURA_TB(
    ID_FACTURA NUMBER,
    ID_MONEDA NUMBER,
    IMPUESTO NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    TOTAL NUMBER(10,2),
    FECHA_FACTURA DATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_FACTURA_PK_ID_FACTURA PRIMARY KEY(ID_FACTURA),
    CONSTRAINT FIDE_FACTURA_FK_ID_MONEDA FOREIGN KEY(ID_MONEDA)
        REFERENCES FIDE_MONEDA_TB(ID_MONEDA),
    CONSTRAINT FIDE_FACTURA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_VENTA_FACTURA_TB(
    ID_VENTA NUMBER,
    ID_FACTURA NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_VENTA_FACTURA_PK_ID_VENTA_ID_FACTURA PRIMARY KEY(ID_VENTA, ID_FACTURA),
    CONSTRAINT FIDE_VENTA_FACTURA_FK_ID_VENTA FOREIGN KEY(ID_VENTA)
        REFERENCES FIDE_VENTA_TB(ID_VENTA),
    CONSTRAINT FIDE_VENTA_FACTURA_FK_ID_FACTURA FOREIGN KEY(ID_FACTURA)
        REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_VENTA_FACTURA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TICKET_FACTURA_TB(
    ID_TICKET NUMBER,
    ID_FACTURA NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_TICKET_FACTURA_PK_ID_TICKET_ID_FACTURA PRIMARY KEY(ID_TICKET, ID_FACTURA),
    CONSTRAINT FIDE_TICKET_FACTURA_FK_ID_TICKET FOREIGN KEY(ID_TICKET)
        REFERENCES FIDE_TICKET_TB(ID_TICKET),
    CONSTRAINT FIDE_TICKET_FACTURA_FK_ID_FACTURA FOREIGN KEY(ID_FACTURA)
        REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_TICKET_FACTURA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_PAGO_PAYPAL_TB(
    ID_PAGO NUMBER,
    ID_FACTURA NUMBER,
    PAYPAL_ORDER_ID VARCHAR2(100),
    PAYPAL_CAPTURE_ID VARCHAR2(100),
    FECHA_PAGO DATE,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_PAGO_PAYPAL_PK_ID_PAGO PRIMARY KEY(ID_PAGO),
    CONSTRAINT FIDE_PAGO_PAYPAL_FK_ID_FACTURA FOREIGN KEY(ID_FACTURA)
        REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_PAGO_PAYPAL_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO MUSICA */
CREATE TABLE FIDE_SEASON_TB(
    ID_SEASON NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_SEASON_PK_ID_SEASON PRIMARY KEY(ID_SEASON),
    CONSTRAINT FIDE_SEASON_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_SEASON_SET_TB(
    ID_SEASON_SET NUMBER,
    ID_SEASON NUMBER,
    TITULO VARCHAR2(100),
    DESCRIPCION VARCHAR2(500),
    YOUTUBE_URL VARCHAR2(300),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_SEASON_SET_PK_ID_SEASON_SET PRIMARY KEY(ID_SEASON_SET),
    CONSTRAINT FIDE_SEASON_SET_FK_ID_SEASON FOREIGN KEY(ID_SEASON)
        REFERENCES FIDE_SEASON_TB(ID_SEASON),
    CONSTRAINT FIDE_SEASON_SET_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO REDES SOCIALES */
CREATE TABLE FIDE_RED_SOCIAL_TB(
    ID_RED_SOCIAL NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_RED_SOCIAL_PK_ID_RED_SOCIAL PRIMARY KEY(ID_RED_SOCIAL),
    CONSTRAINT FIDE_RED_SOCIAL_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CUENTA_RED_SOCIAL_TB(
    IDENTIFICACION NUMBER,
    ID_RED_SOCIAL NUMBER,
    URL VARCHAR2(300),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CUENTA_RED_SOCIAL_PK_IDENTIFICACION_ID_RED_SOCIAL PRIMARY KEY(IDENTIFICACION, ID_RED_SOCIAL),
    CONSTRAINT FIDE_CUENTA_RED_SOCIAL_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_CUENTA_RED_SOCIAL_FK_ID_RED_SOCIAL FOREIGN KEY(ID_RED_SOCIAL)
        REFERENCES FIDE_RED_SOCIAL_TB(ID_RED_SOCIAL),
    CONSTRAINT FIDE_CUENTA_RED_SOCIAL_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO CARRITO DE COMPRAS */
CREATE TABLE FIDE_CARRITO_TB(
    ID_CARRITO NUMBER,
    ID_CUENTA NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CARRITO_PK_ID_CARRITO PRIMARY KEY(ID_CARRITO),
    CONSTRAINT FIDE_CARRITO_FK_ID_CUENTA FOREIGN KEY(ID_CUENTA)
        REFERENCES FIDE_CUENTA_TB(ID_CUENTA),
    CONSTRAINT FIDE_CARRITO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CARRITO_ITEM_TB(
    ID_CARRITO NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_CARRITO_ITEM_PK_ID_CARRITO_ID_PRODUCTO PRIMARY KEY(ID_CARRITO, ID_PRODUCTO),
    CONSTRAINT FIDE_CARRITO_ITEM_FK_ID_CARRITO FOREIGN KEY(ID_CARRITO)
        REFERENCES FIDE_CARRITO_TB(ID_CARRITO),
    CONSTRAINT FIDE_CARRITO_ITEM_FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FIDE_CARRITO_ITEM_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

/* MODULO AUDITORIA */
CREATE TABLE FIDE_AUDITORIA_TB(
    ID_AUDITORIA NUMBER,
    IDENTIFICACION NUMBER,
    ENTIDAD VARCHAR2(100),
    ACCION VARCHAR2(100),
    USUARIO VARCHAR2(100),
    FECHA DATE,
    DETALLE VARCHAR2(500),
    ID_ESTADO NUMBER,

    CONSTRAINT FIDE_AUDITORIA_PK_ID_AUDITORIA PRIMARY KEY(ID_AUDITORIA),
    CONSTRAINT FIDE_AUDITORIA_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_AUDITORIA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
         REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
