CREATE PROFILE ADMIN_PROFILE LIMIT
SESSIONS_PER_USER 10
IDLE_TIME 30
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME 7
PASSWORD_REUSE_TIME 180
PASSWORD_REUSE_MAX 5
PASSWORD_VERIFY_FUNCTION ADMIN.DANCEROOM_VERIFY_PASSWORD;
/

CREATE PROFILE DESAROLLADOR_PROFILE LIMIT
SESSIONS_PER_USER 5
IDLE_TIME 15
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME 7
PASSWORD_REUSE_TIME 180
PASSWORD_REUSE_MAX 5
PASSWORD_VERIFY_FUNCTION ADMIN.DANCEROOM_VERIFY_PASSWORD;
/

CREATE PROFILE ANALISTA_PROFILE LIMIT
SESSIONS_PER_USER 2
IDLE_TIME 5
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME 7
PASSWORD_REUSE_TIME 180
PASSWORD_REUSE_MAX 5
PASSWORD_VERIFY_FUNCTION ADMIN.DANCEROOM_VERIFY_PASSWORD;
/
