-- CREACION USUARIO DANCERROM (SCHEMA DUENO DEL PROYECTO) --

CREATE USER DANCERROM
IDENTIFIED BY DbDance#2026Own
QUOTA 500M ON USERS;

GRANT CREATE SESSION TO DANCERROM;
GRANT CREATE TABLE TO DANCERROM;
GRANT CREATE VIEW TO DANCERROM;
GRANT CREATE MATERIALIZED VIEW TO DANCERROM;
GRANT CREATE SEQUENCE TO DANCERROM;
GRANT CREATE PROCEDURE TO DANCERROM;
GRANT CREATE TRIGGER TO DANCERROM;

COMMIT;
