-- Creación de roles con grants específicos
CREATE ROLE ADMIN_ROLE;

-- Grants completos en todas las tablas
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_ESTADO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_TIPO_USUARIO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_PAIS_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_PROVINCIA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CANTON_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_DISTRITO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_DIRECCION_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_USUARIO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CORREO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_TELEFONO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CUENTA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_TIPO_OTP_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CODIGO_OTP_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_REFRESH_TOKEN_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CATEGORIA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_PRODUCTO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_INVENTARIO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_TIPO_MOVIMIENTO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_MOVIMIENTO_INVENTARIO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_VENTA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_VENTA_PRODUCTO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_EVENTO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_TIPO_CONTENIDO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CONTENIDO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_TIPO_TICKET_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_EVENTO_TICKET TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_TICKET_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_MONEDA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_FACTURA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_VENTA_FACTURA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_TICKET_FACTURA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_PAGO_PAYPAL_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_SEASON_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_SEASON_SET_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_RED_SOCIAL_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CUENTA_RED_SOCIAL_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CARRITO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CARRITO_ITEM_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_AUDITORIA_TB TO ADMIN_ROLE;

-- Grants de lectura en vistas normales y materializadas
GRANT SELECT ON DANCEROOM.FIDE_USUARIO_COMPLETO_V TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_CARRITO_ACTIVO_V TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_EVENTOS_DISPONIBLES_V TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_MIS_TICKETS_V TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_PRODUCTOS_STOCK_V TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_HISTORIAL_COMPRAS_V TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_TOP_PRODUCTOS_VM TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_VENTAS_MENSUALES_VM TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_RECAUDACION_EVENTOS_VM TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_INVENTARIO_VALORIZADO_VM TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_TOP_CLIENTES_VM TO ADMIN_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_FACTURACION_MENSUAL_VM TO ADMIN_ROLE;
/

CREATE ROLE DESAROLLADOR_ROLE;
-- Grants solo en tablas importantes: usuario, producto, venta, evento, cuenta
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_USUARIO_TB TO DESAROLLADOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_CUENTA_TB TO DESAROLLADOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_PRODUCTO_TB TO DESAROLLADOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_VENTA_TB TO DESAROLLADOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANCEROOM.FIDE_EVENTO_TB TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_USUARIO_COMPLETO_V TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_CARRITO_ACTIVO_V TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_EVENTOS_DISPONIBLES_V TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_MIS_TICKETS_V TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_PRODUCTOS_STOCK_V TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_HISTORIAL_COMPRAS_V TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_TOP_PRODUCTOS_VM TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_VENTAS_MENSUALES_VM TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_RECAUDACION_EVENTOS_VM TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_INVENTARIO_VALORIZADO_VM TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_TOP_CLIENTES_VM TO DESAROLLADOR_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_FACTURACION_MENSUAL_VM TO DESAROLLADOR_ROLE;
/

CREATE ROLE ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_ESTADO_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_TIPO_USUARIO_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_USUARIO_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_CORREO_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_TELEFONO_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_CUENTA_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_CATEGORIA_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_PRODUCTO_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_VENTA_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_EVENTO_TB TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_USUARIO_COMPLETO_V TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_CARRITO_ACTIVO_V TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_EVENTOS_DISPONIBLES_V TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_MIS_TICKETS_V TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_PRODUCTOS_STOCK_V TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_HISTORIAL_COMPRAS_V TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_TOP_PRODUCTOS_VM TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_VENTAS_MENSUALES_VM TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_RECAUDACION_EVENTOS_VM TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_INVENTARIO_VALORIZADO_VM TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_TOP_CLIENTES_VM TO ANALISTA_ROLE;
GRANT SELECT ON DANCEROOM.FIDE_FACTURACION_MENSUAL_VM TO ANALISTA_ROLE;
/
commit;