-- Creación de usuarios con roles específicos
CREATE USER ADMIN_DANCEROOM
IDENTIFIED BY DbDance#2026Adm;
GRANT CREATE SESSION TO ADMIN_DANCEROOM;
GRANT ADMIN_ROLE TO ADMIN_DANCEROOM;
ALTER USER ADMIN_DANCEROOM PROFILE ADMIN_PROFILE;

-- Usuario DESAROLLADOR: Permisos para consultar y modificar datos (desarrollo)
CREATE USER DESAROLLADOR_DANCEROOM
IDENTIFIED BY DbDance#2026Dev;
GRANT CREATE SESSION TO DESAROLLADOR_DANCEROOM;
GRANT DESAROLLADOR_ROLE TO DESAROLLADOR_DANCEROOM;
ALTER USER DESAROLLADOR_DANCEROOM PROFILE DESAROLLADOR_PROFILE;

-- Usuario ANALISTA: Solo permisos de lectura (análisis)
CREATE USER ANALISTA_DANCEROOM
IDENTIFIED BY DbDance#2026Ana;
GRANT CREATE SESSION TO ANALISTA_DANCEROOM;
GRANT ANALISTA_ROLE TO ANALISTA_DANCEROOM;
ALTER USER ANALISTA_DANCEROOM PROFILE ANALISTA_PROFILE;

COMMIT;
