-- Creación de perfiles de usuario con restricciones
CREATE PROFILE ADMIN_PROFILE LIMIT
SESSIONS_PER_USER 10
IDLE_TIME 30
CPU_PER_SESSION 10000
LOGICAL_READS_PER_SESSION 100000
CONNECT_TIME 480
PRIVATE_SGA 1M;
/

CREATE PROFILE DESAROLLADOR_PROFILE LIMIT
SESSIONS_PER_USER 5
IDLE_TIME 15
CPU_PER_SESSION 5000
LOGICAL_READS_PER_SESSION 50000
CONNECT_TIME 240
PRIVATE_SGA 512K;
/

CREATE PROFILE ANALISTA_PROFILE LIMIT
SESSIONS_PER_USER 2
IDLE_TIME 5
CPU_PER_SESSION 1000
LOGICAL_READS_PER_SESSION 10000
CONNECT_TIME 60
PRIVATE_SGA 256K;
/

