-- DROP DE USUARIOS, ROLES, PERFILES Y FUNCION DE PASSWORD DEL PROYECTO
-- Ejecutar conectado como SYS/DBA antes de volver a levantar los scripts.

-- 1. Usuarios finales y esquema dueno
BEGIN
    EXECUTE IMMEDIATE 'DROP USER ANALISTA_DANCEROOM CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER DESAROLLADOR_DANCEROOM CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER ADMIN_DANCEROOM CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER DANCERROM CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER MAESTRO_PROYECTO CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

-- 2. Roles del proyecto
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ANALISTA_ROLE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1919 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE DESAROLLADOR_ROLE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1919 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ADMIN_ROLE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1919 THEN
            RAISE;
        END IF;
END;
/

-- 3. Perfiles del proyecto
BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE ANALISTA_PROFILE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2380 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE DESAROLLADOR_PROFILE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2380 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE ADMIN_PROFILE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2380 THEN
            RAISE;
        END IF;
END;
/

-- 4. Funcion de verificacion de passwords
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION DANCERROM_VERIFY_PASSWORD';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/
