-- ============================================================
-- MÓDULO ESTADO
-- ============================================================

-- Búsqueda por nombre de estado (filtros generales)
CREATE INDEX FIDE_ESTADO_IDX_NOMBRE
    ON FIDE_ESTADO_TB(NOMBRE_ESTADO);
/

-- ============================================================
-- MÓDULO USUARIO
-- ============================================================

-- FK: FIDE_TIPO_USUARIO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_TIPO_USUARIO_IDX_ID_ESTADO
    ON FIDE_TIPO_USUARIO_TB(ID_ESTADO);
/

-- FK: FIDE_USUARIO_TB -> FIDE_DIRECCION_TB
CREATE INDEX FIDE_USUARIO_IDX_ID_DIRECCION
    ON FIDE_USUARIO_TB(ID_DIRECCION);
/

-- FK: FIDE_USUARIO_TB -> FIDE_TIPO_USUARIO_TB
CREATE INDEX FIDE_USUARIO_IDX_ID_TIPO_USUARIO
    ON FIDE_USUARIO_TB(ID_TIPO_USUARIO);
/

-- FK: FIDE_USUARIO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_USUARIO_IDX_ID_ESTADO
    ON FIDE_USUARIO_TB(ID_ESTADO);
/

-- Búsqueda por nombre y apellidos
CREATE INDEX FIDE_USUARIO_IDX_NOMBRE
    ON FIDE_USUARIO_TB(NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO);
/

-- FK: FIDE_CORREO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CORREO_IDX_ID_ESTADO
    ON FIDE_CORREO_TB(ID_ESTADO);
/

-- Búsqueda por correo (login, validaciones de unicidad)
CREATE INDEX FIDE_CORREO_IDX_CORREO
    ON FIDE_CORREO_TB(CORREO);
/

-- FK: FIDE_TELEFONO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_TELEFONO_IDX_ID_ESTADO
    ON FIDE_TELEFONO_TB(ID_ESTADO);
/

-- Búsqueda por número de teléfono
CREATE INDEX FIDE_TELEFONO_IDX_TELEFONO
    ON FIDE_TELEFONO_TB(TELEFONO);
/

-- ============================================================
-- MÓDULO DIRECCIÓN
-- ============================================================

-- FK: FIDE_PAIS_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_PAIS_IDX_ID_ESTADO
    ON FIDE_PAIS_TB(ID_ESTADO);
/

-- FK: FIDE_PROVINCIA_TB -> FIDE_PAIS_TB
CREATE INDEX FIDE_PROVINCIA_IDX_ID_PAIS
    ON FIDE_PROVINCIA_TB(ID_PAIS);
/

-- FK: FIDE_PROVINCIA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_PROVINCIA_IDX_ID_ESTADO
    ON FIDE_PROVINCIA_TB(ID_ESTADO);
/

-- FK: FIDE_CANTON_TB -> FIDE_PROVINCIA_TB
CREATE INDEX FIDE_CANTON_IDX_ID_PROVINCIA
    ON FIDE_CANTON_TB(ID_PROVINCIA);
/

-- FK: FIDE_CANTON_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CANTON_IDX_ID_ESTADO
    ON FIDE_CANTON_TB(ID_ESTADO);
/

-- FK: FIDE_DISTRITO_TB -> FIDE_CANTON_TB
CREATE INDEX FIDE_DISTRITO_IDX_ID_CANTON
    ON FIDE_DISTRITO_TB(ID_CANTON);
/

-- FK: FIDE_DISTRITO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_DISTRITO_IDX_ID_ESTADO
    ON FIDE_DISTRITO_TB(ID_ESTADO);
/

-- FK: FIDE_DIRECCION_TB -> FIDE_DISTRITO_TB
CREATE INDEX FIDE_DIRECCION_IDX_ID_DISTRITO
    ON FIDE_DIRECCION_TB(ID_DISTRITO);
/

-- FK: FIDE_DIRECCION_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_DIRECCION_IDX_ID_ESTADO
    ON FIDE_DIRECCION_TB(ID_ESTADO);
/

-- ============================================================
-- MÓDULO AUTENTICACIÓN
-- ============================================================

-- FK: FIDE_CUENTA_TB -> FIDE_USUARIO_TB
CREATE INDEX FIDE_CUENTA_IDX_IDENTIFICACION
    ON FIDE_CUENTA_TB(IDENTIFICACION);
/

-- FK: FIDE_CUENTA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CUENTA_IDX_ID_ESTADO
    ON FIDE_CUENTA_TB(ID_ESTADO);
/

-- Búsqueda por nombre de usuario (login)
CREATE INDEX FIDE_CUENTA_IDX_USUARIO
    ON FIDE_CUENTA_TB(USUARIO);
/

-- FK: FIDE_TIPO_OTP_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_TIPO_OTP_IDX_ID_ESTADO
    ON FIDE_TIPO_OTP_TB(ID_ESTADO);
/

-- FK: FIDE_CODIGO_OTP_TB -> FIDE_CUENTA_TB
CREATE INDEX FIDE_CODIGO_OTP_IDX_ID_CUENTA
    ON FIDE_CODIGO_OTP_TB(ID_CUENTA);
/

-- FK: FIDE_CODIGO_OTP_TB -> FIDE_TIPO_OTP_TB
CREATE INDEX FIDE_CODIGO_OTP_IDX_ID_TIPO_OTP
    ON FIDE_CODIGO_OTP_TB(ID_TIPO_OTP);
/

-- FK: FIDE_CODIGO_OTP_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CODIGO_OTP_IDX_ID_ESTADO
    ON FIDE_CODIGO_OTP_TB(ID_ESTADO);
/

-- Consulta de OTPs no expirados y activos
CREATE INDEX FIDE_CODIGO_OTP_IDX_FECHA_EXPIRACION
    ON FIDE_CODIGO_OTP_TB(FECHA_EXPIRACION);
/

-- FK: FIDE_REFRESH_TOKEN_TB -> FIDE_CUENTA_TB
CREATE INDEX FIDE_REFRESH_TOKEN_IDX_ID_CUENTA
    ON FIDE_REFRESH_TOKEN_TB(ID_CUENTA);
/

-- FK: FIDE_REFRESH_TOKEN_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_REFRESH_TOKEN_IDX_ID_ESTADO
    ON FIDE_REFRESH_TOKEN_TB(ID_ESTADO);
/

-- Búsqueda de token por JTI (validación JWT)
CREATE INDEX FIDE_REFRESH_TOKEN_IDX_JTI
    ON FIDE_REFRESH_TOKEN_TB(JTI);
/

-- Consulta de tokens por expiración (limpieza / renovación)
CREATE INDEX FIDE_REFRESH_TOKEN_IDX_FECHA_EXPIRACION
    ON FIDE_REFRESH_TOKEN_TB(FECHA_EXPIRACION);
/

-- ============================================================
-- MÓDULO PRODUCTOS
-- ============================================================

-- FK: FIDE_CATEGORIA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CATEGORIA_IDX_ID_ESTADO
    ON FIDE_CATEGORIA_TB(ID_ESTADO);
/

-- FK: FIDE_PRODUCTO_TB -> FIDE_CATEGORIA_TB
CREATE INDEX FIDE_PRODUCTO_IDX_ID_CATEGORIA
    ON FIDE_PRODUCTO_TB(ID_CATEGORIA);
/

-- FK: FIDE_PRODUCTO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_PRODUCTO_IDX_ID_ESTADO
    ON FIDE_PRODUCTO_TB(ID_ESTADO);
/

-- Búsqueda de productos por nombre
CREATE INDEX FIDE_PRODUCTO_IDX_NOMBRE
    ON FIDE_PRODUCTO_TB(NOMBRE);
/

-- Filtro de productos por rango de precio
CREATE INDEX FIDE_PRODUCTO_IDX_PRECIO
    ON FIDE_PRODUCTO_TB(PRECIO);
/

-- ============================================================
-- MÓDULO INVENTARIO
-- ============================================================

-- FK: FIDE_INVENTARIO_TB -> FIDE_PRODUCTO_TB
CREATE INDEX FIDE_INVENTARIO_IDX_ID_PRODUCTO
    ON FIDE_INVENTARIO_TB(ID_PRODUCTO);
/

-- FK: FIDE_INVENTARIO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_INVENTARIO_IDX_ID_ESTADO
    ON FIDE_INVENTARIO_TB(ID_ESTADO);
/

-- FK: FIDE_TIPO_MOVIMIENTO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_TIPO_MOVIMIENTO_IDX_ID_ESTADO
    ON FIDE_TIPO_MOVIMIENTO_TB(ID_ESTADO);
/

-- FK: FIDE_MOVIMIENTO_INVENTARIO_TB -> FIDE_PRODUCTO_TB
CREATE INDEX FIDE_MOV_INVENTARIO_IDX_ID_PRODUCTO
    ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_PRODUCTO);
/

-- FK: FIDE_MOVIMIENTO_INVENTARIO_TB -> FIDE_TIPO_MOVIMIENTO_TB
CREATE INDEX FIDE_MOV_INVENTARIO_IDX_ID_TIPO_MOV
    ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_TIPO_MOVIMIENTO);
/

-- FK: FIDE_MOVIMIENTO_INVENTARIO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_MOV_INVENTARIO_IDX_ID_ESTADO
    ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_ESTADO);
/

-- Filtro de movimientos por fecha (reportes de inventario)
CREATE INDEX FIDE_MOV_INVENTARIO_IDX_FECHA
    ON FIDE_MOVIMIENTO_INVENTARIO_TB(FECHA_MOVIMIENTO);
/

-- ============================================================
-- MÓDULO TIENDA
-- ============================================================

-- FK: FIDE_VENTA_TB -> FIDE_CUENTA_TB
CREATE INDEX FIDE_VENTA_IDX_ID_CUENTA
    ON FIDE_VENTA_TB(ID_CUENTA);
/

-- FK: FIDE_VENTA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_VENTA_IDX_ID_ESTADO
    ON FIDE_VENTA_TB(ID_ESTADO);
/

-- Filtro de ventas por fecha (reportes de tienda)
CREATE INDEX FIDE_VENTA_IDX_FECHA_VENTA
    ON FIDE_VENTA_TB(FECHA_VENTA);
/

-- FK: FIDE_VENTA_PRODUCTO_TB -> FIDE_PRODUCTO_TB
CREATE INDEX FIDE_VENTA_PRODUCTO_IDX_ID_PRODUCTO
    ON FIDE_VENTA_PRODUCTO_TB(ID_PRODUCTO);
/

-- FK: FIDE_VENTA_PRODUCTO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_VENTA_PRODUCTO_IDX_ID_ESTADO
    ON FIDE_VENTA_PRODUCTO_TB(ID_ESTADO);
/

-- ============================================================
-- MÓDULO EVENTOS
-- ============================================================

-- FK: FIDE_EVENTO_TB -> FIDE_DIRECCION_TB
CREATE INDEX FIDE_EVENTO_IDX_ID_DIRECCION
    ON FIDE_EVENTO_TB(ID_DIRECCION);
/

-- FK: FIDE_EVENTO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_EVENTO_IDX_ID_ESTADO
    ON FIDE_EVENTO_TB(ID_ESTADO);
/

-- Búsqueda de eventos por fecha (próximos eventos)
CREATE INDEX FIDE_EVENTO_IDX_FECHA_EVENTO
    ON FIDE_EVENTO_TB(FECHA_EVENTO);
/

-- Búsqueda de eventos por título
CREATE INDEX FIDE_EVENTO_IDX_TITULO
    ON FIDE_EVENTO_TB(TITULO);
/

-- FK: FIDE_TIPO_CONTENIDO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_TIPO_CONTENIDO_IDX_ID_ESTADO
    ON FIDE_TIPO_CONTENIDO_TB(ID_ESTADO);
/

-- FK: FIDE_CONTENIDO_TB -> FIDE_EVENTO_TB
CREATE INDEX FIDE_CONTENIDO_IDX_ID_EVENTO
    ON FIDE_CONTENIDO_TB(ID_EVENTO);
/

-- FK: FIDE_CONTENIDO_TB -> FIDE_TIPO_CONTENIDO_TB
CREATE INDEX FIDE_CONTENIDO_IDX_ID_TIPO_CONTENIDO
    ON FIDE_CONTENIDO_TB(ID_TIPO_CONTENIDO);
/

-- FK: FIDE_CONTENIDO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CONTENIDO_IDX_ID_ESTADO
    ON FIDE_CONTENIDO_TB(ID_ESTADO);
/

-- ============================================================
-- MÓDULO BOLETERÍA / TICKETS
-- ============================================================

-- FK: FIDE_TIPO_TICKET_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_TIPO_TICKET_IDX_ID_ESTADO
    ON FIDE_TIPO_TICKET_TB(ID_ESTADO);
/

-- FK: FIDE_EVENTO_TICKET -> FIDE_EVENTO_TB
CREATE INDEX FIDE_EVENTO_TICKET_IDX_ID_EVENTO
    ON FIDE_EVENTO_TICKET(ID_EVENTO);
/

-- FK: FIDE_EVENTO_TICKET -> FIDE_TIPO_TICKET_TB
CREATE INDEX FIDE_EVENTO_TICKET_IDX_ID_TIPO_TICKET
    ON FIDE_EVENTO_TICKET(ID_TIPO_TICKET);
/

-- FK: FIDE_EVENTO_TICKET -> FIDE_ESTADO_TB
CREATE INDEX FIDE_EVENTO_TICKET_IDX_ID_ESTADO
    ON FIDE_EVENTO_TICKET(ID_ESTADO);
/

-- Consulta de disponibilidad de tickets (cupos)
CREATE INDEX FIDE_EVENTO_TICKET_IDX_CUPOS
    ON FIDE_EVENTO_TICKET(CUPOS_DISPONIBLES, FECHA_INICIO, FECHA_FIN);
/

-- FK: FIDE_TICKET_TB -> FIDE_EVENTO_TICKET
CREATE INDEX FIDE_TICKET_IDX_ID_EVENTO_TICKET
    ON FIDE_TICKET_TB(ID_EVENTO_TICKET);
/

-- FK: FIDE_TICKET_TB -> FIDE_CUENTA_TB
CREATE INDEX FIDE_TICKET_IDX_ID_CUENTA
    ON FIDE_TICKET_TB(ID_CUENTA);
/

-- FK: FIDE_TICKET_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_TICKET_IDX_ID_ESTADO
    ON FIDE_TICKET_TB(ID_ESTADO);
/

-- Búsqueda de ticket por código QR
CREATE UNIQUE INDEX FIDE_TICKET_IDX_CODIGO_QR
    ON FIDE_TICKET_TB(CODIGO_QR);
/

-- ============================================================
-- MÓDULO FACTURACIÓN
-- ============================================================

-- FK: FIDE_MONEDA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_MONEDA_IDX_ID_ESTADO
    ON FIDE_MONEDA_TB(ID_ESTADO);
/

-- FK: FIDE_FACTURA_TB -> FIDE_MONEDA_TB
CREATE INDEX FIDE_FACTURA_IDX_ID_MONEDA
    ON FIDE_FACTURA_TB(ID_MONEDA);
/

-- FK: FIDE_FACTURA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_FACTURA_IDX_ID_ESTADO
    ON FIDE_FACTURA_TB(ID_ESTADO);
/

-- Filtro de facturas por fecha
CREATE INDEX FIDE_FACTURA_IDX_FECHA_FACTURA
    ON FIDE_FACTURA_TB(FECHA_FACTURA);
/

-- FK: FIDE_VENTA_FACTURA_TB -> FIDE_FACTURA_TB
CREATE INDEX FIDE_VENTA_FACTURA_IDX_ID_FACTURA
    ON FIDE_VENTA_FACTURA_TB(ID_FACTURA);
/

-- FK: FIDE_VENTA_FACTURA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_VENTA_FACTURA_IDX_ID_ESTADO
    ON FIDE_VENTA_FACTURA_TB(ID_ESTADO);
/

-- FK: FIDE_TICKET_FACTURA_TB -> FIDE_FACTURA_TB
CREATE INDEX FIDE_TICKET_FACTURA_IDX_ID_FACTURA
    ON FIDE_TICKET_FACTURA_TB(ID_FACTURA);
/

-- FK: FIDE_TICKET_FACTURA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_TICKET_FACTURA_IDX_ID_ESTADO
    ON FIDE_TICKET_FACTURA_TB(ID_ESTADO);
/

-- FK: FIDE_PAGO_PAYPAL_TB -> FIDE_FACTURA_TB
CREATE INDEX FIDE_PAGO_PAYPAL_IDX_ID_FACTURA
    ON FIDE_PAGO_PAYPAL_TB(ID_FACTURA);
/

-- FK: FIDE_PAGO_PAYPAL_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_PAGO_PAYPAL_IDX_ID_ESTADO
    ON FIDE_PAGO_PAYPAL_TB(ID_ESTADO);
/

-- Búsqueda de pago por PAYPAL_ORDER_ID (conciliación)
CREATE INDEX FIDE_PAGO_PAYPAL_IDX_ORDER_ID
    ON FIDE_PAGO_PAYPAL_TB(PAYPAL_ORDER_ID);
/

-- Búsqueda de pago por PAYPAL_CAPTURE_ID
CREATE INDEX FIDE_PAGO_PAYPAL_IDX_CAPTURE_ID
    ON FIDE_PAGO_PAYPAL_TB(PAYPAL_CAPTURE_ID);
/

-- ============================================================
-- MÓDULO MÚSICA (SEASON)
-- ============================================================

-- FK: FIDE_SEASON_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_SEASON_IDX_ID_ESTADO
    ON FIDE_SEASON_TB(ID_ESTADO);
/

-- FK: FIDE_SEASON_SET_TB -> FIDE_SEASON_TB
CREATE INDEX FIDE_SEASON_SET_IDX_ID_SEASON
    ON FIDE_SEASON_SET_TB(ID_SEASON);
/

-- FK: FIDE_SEASON_SET_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_SEASON_SET_IDX_ID_ESTADO
    ON FIDE_SEASON_SET_TB(ID_ESTADO);
/

-- ============================================================
-- MÓDULO REDES SOCIALES
-- ============================================================

-- FK: FIDE_RED_SOCIAL_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_RED_SOCIAL_IDX_ID_ESTADO
    ON FIDE_RED_SOCIAL_TB(ID_ESTADO);
/

-- FK: FIDE_CUENTA_RED_SOCIAL_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CUENTA_RED_SOCIAL_IDX_ID_ESTADO
    ON FIDE_CUENTA_RED_SOCIAL_TB(ID_ESTADO);
/

-- ============================================================
-- MÓDULO CARRITO DE COMPRAS
-- ============================================================

-- FK: FIDE_CARRITO_TB -> FIDE_CUENTA_TB
CREATE INDEX FIDE_CARRITO_IDX_ID_CUENTA
    ON FIDE_CARRITO_TB(ID_CUENTA);
/

-- FK: FIDE_CARRITO_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CARRITO_IDX_ID_ESTADO
    ON FIDE_CARRITO_TB(ID_ESTADO);
/

-- FK: FIDE_CARRITO_ITEM_TB -> FIDE_PRODUCTO_TB
CREATE INDEX FIDE_CARRITO_ITEM_IDX_ID_PRODUCTO
    ON FIDE_CARRITO_ITEM_TB(ID_PRODUCTO);
/

-- FK: FIDE_CARRITO_ITEM_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_CARRITO_ITEM_IDX_ID_ESTADO
    ON FIDE_CARRITO_ITEM_TB(ID_ESTADO);
/

-- ============================================================
-- MÓDULO AUDITORÍA
-- ============================================================

-- FK: FIDE_AUDITORIA_TB -> FIDE_USUARIO_TB
CREATE INDEX FIDE_AUDITORIA_IDX_IDENTIFICACION
    ON FIDE_AUDITORIA_TB(IDENTIFICACION);
/

-- FK: FIDE_AUDITORIA_TB -> FIDE_ESTADO_TB
CREATE INDEX FIDE_AUDITORIA_IDX_ID_ESTADO
    ON FIDE_AUDITORIA_TB(ID_ESTADO);
/

-- Filtro de auditoría por fecha (trazabilidad)
CREATE INDEX FIDE_AUDITORIA_IDX_FECHA
    ON FIDE_AUDITORIA_TB(FECHA);
/

-- Filtro de auditoría por entidad afectada
CREATE INDEX FIDE_AUDITORIA_IDX_ENTIDAD
    ON FIDE_AUDITORIA_TB(ENTIDAD);
/

-- Filtro de auditoría por acción (INSERT, UPDATE, DELETE)
CREATE INDEX FIDE_AUDITORIA_IDX_ACCION
    ON FIDE_AUDITORIA_TB(ACCION);
/

-- Búsqueda combinada: entidad + acción + fecha (consultas de auditoría)
CREATE INDEX FIDE_AUDITORIA_IDX_ENTIDAD_ACCION_FECHA
    ON FIDE_AUDITORIA_TB(ENTIDAD, ACCION, FECHA);
/

COMMIT