CREATE TABLE FIDE_FACTURA_PART_TB(
    ID_FACTURA      NUMBER,
    ID_MONEDA       NUMBER,
    IMPUESTO        NUMBER(10,2),
    SUBTOTAL        NUMBER(10,2),
    TOTAL           NUMBER(10,2),
    FECHA_FACTURA   DATE,
    ID_ESTADO       NUMBER,

    CONSTRAINT FIDE_FACTURA_PART_PK_ID_FACTURA PRIMARY KEY(ID_FACTURA),
    CONSTRAINT FIDE_FACTURA_PART_FK_ID_MONEDA FOREIGN KEY(ID_MONEDA)
        REFERENCES FIDE_MONEDA_TB(ID_MONEDA),
    CONSTRAINT FIDE_FACTURA_PART_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
)
PARTITION BY RANGE (FECHA_FACTURA) (
    PARTITION FACTURA_2022 VALUES LESS THAN (TO_DATE('01/01/2023', 'DD/MM/YYYY')),
    PARTITION FACTURA_2023 VALUES LESS THAN (TO_DATE('01/01/2024', 'DD/MM/YYYY')),
    PARTITION FACTURA_2024 VALUES LESS THAN (TO_DATE('01/01/2025', 'DD/MM/YYYY')),
    PARTITION FACTURA_2025 VALUES LESS THAN (TO_DATE('01/01/2026', 'DD/MM/YYYY')),
    PARTITION FACTURA_2026 VALUES LESS THAN (TO_DATE('01/01/2027', 'DD/MM/YYYY')),
    PARTITION FACTURA_FUTURO VALUES LESS THAN (MAXVALUE)
);
