---PARA QUE LAS PARTICIONES EMPIECEN A TRABAJAR DEBO DE ANALIZAR TODA LA TABLA---
ANALYZE TABLE FIDE_FACTURA_TB COMPUTE STATISTICS;

-- Verifica que la tabla este particionada
SELECT TABLE_NAME, PARTITIONED
FROM USER_TABLES
WHERE TABLE_NAME = 'FIDE_FACTURA_TB';

-- Muestra estadisticas de cada particion
SELECT PARTITION_POSITION,
       PARTITION_NAME,
       NUM_ROWS,
       LAST_ANALYZED
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'FIDE_FACTURA_TB'
ORDER BY PARTITION_POSITION;

-- Conteo rapido para validar que hay datos en cada particion
SELECT 'FACTURA_2022' AS PARTICION, COUNT(*) AS TOTAL
FROM FIDE_FACTURA_TB PARTITION (FACTURA_2022)
UNION ALL
SELECT 'FACTURA_2023', COUNT(*)
FROM FIDE_FACTURA_TB PARTITION (FACTURA_2023)
UNION ALL
SELECT 'FACTURA_2024', COUNT(*)
FROM FIDE_FACTURA_TB PARTITION (FACTURA_2024)
UNION ALL
SELECT 'FACTURA_2025', COUNT(*)
FROM FIDE_FACTURA_TB PARTITION (FACTURA_2025)
UNION ALL
SELECT 'FACTURA_2026', COUNT(*)
FROM FIDE_FACTURA_TB PARTITION (FACTURA_2026)
UNION ALL
SELECT 'FACTURA_FUTURO', COUNT(*)
FROM FIDE_FACTURA_TB PARTITION (FACTURA_FUTURO);

-- Ejemplo de lectura directa de una particion
SELECT ID_FACTURA, FECHA_FACTURA, TOTAL
FROM FIDE_FACTURA_TB PARTITION (FACTURA_2024)
ORDER BY FECHA_FACTURA;

-- Ejemplo para comprobar partition pruning
EXPLAIN PLAN FOR
SELECT ID_FACTURA, FECHA_FACTURA, TOTAL
FROM FIDE_FACTURA_TB
WHERE FECHA_FACTURA >= DATE '2024-01-01'
  AND FECHA_FACTURA < DATE '2025-01-01';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);


