/* TRIGGERS DE AUDITORIA */

/* MODULO ESTADO */
CREATE OR REPLACE TRIGGER FIDE_ESTADO_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADO_TRG
BEFORE UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO USUARIO */
CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_TRG
BEFORE INSERT ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_TRG
BEFORE UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_TRG
BEFORE INSERT ON FIDE_CORREO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_TRG
BEFORE UPDATE ON FIDE_CORREO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONO_TRG
BEFORE INSERT ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONO_TRG
BEFORE UPDATE ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO DIRECCION */
CREATE OR REPLACE TRIGGER FIDE_PAIS_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_TRG
BEFORE UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TRG
BEFORE UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_TRG
BEFORE UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TRG
BEFORE UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO AUTENTICACION */
CREATE OR REPLACE TRIGGER FIDE_CUENTA_TRG
BEFORE INSERT ON FIDE_CUENTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CUENTA_TRG
BEFORE UPDATE ON FIDE_CUENTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_OTP_TRG
BEFORE INSERT ON FIDE_TIPO_OTP_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_OTP_TRG
BEFORE UPDATE ON FIDE_TIPO_OTP_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CODIGO_OTP_TRG
BEFORE INSERT ON FIDE_CODIGO_OTP_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CODIGO_OTP_TRG
BEFORE UPDATE ON FIDE_CODIGO_OTP_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_REFRESH_TOKEN_TRG
BEFORE INSERT ON FIDE_REFRESH_TOKEN_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_REFRESH_TOKEN_TRG
BEFORE UPDATE ON FIDE_REFRESH_TOKEN_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO PRODUCTOS */
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO INVENTARIO */
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MOV_TRG
BEFORE INSERT ON FIDE_TIPO_MOVIMIENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MOV_TRG
BEFORE UPDATE ON FIDE_TIPO_MOVIMIENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_MOV_INV_TRG
BEFORE INSERT ON FIDE_MOVIMIENTO_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_MOV_INV_TRG
BEFORE UPDATE ON FIDE_MOVIMIENTO_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO TIENDA */
CREATE OR REPLACE TRIGGER FIDE_VENTA_TRG
BEFORE INSERT ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_TRG
BEFORE UPDATE ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_PROD_TRG
BEFORE INSERT ON FIDE_VENTA_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_PROD_TRG
BEFORE UPDATE ON FIDE_VENTA_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO EVENTOS */
CREATE OR REPLACE TRIGGER FIDE_EVENTO_TRG
BEFORE INSERT ON FIDE_EVENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_TRG
BEFORE UPDATE ON FIDE_EVENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_CONT_TRG
BEFORE INSERT ON FIDE_TIPO_CONTENIDO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_CONT_TRG
BEFORE UPDATE ON FIDE_TIPO_CONTENIDO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CONTENIDO_TRG
BEFORE INSERT ON FIDE_CONTENIDO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CONTENIDO_TRG
BEFORE UPDATE ON FIDE_CONTENIDO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO TICKETS */
CREATE OR REPLACE TRIGGER FIDE_TIPO_TICKET_TRG
BEFORE INSERT ON FIDE_TIPO_TICKET_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_TICKET_TRG
BEFORE UPDATE ON FIDE_TIPO_TICKET_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_TICKET_TRG
BEFORE INSERT ON FIDE_EVENTO_TICKET
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_TICKET_TRG
BEFORE UPDATE ON FIDE_EVENTO_TICKET
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TICKET_TRG
BEFORE INSERT ON FIDE_TICKET_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TICKET_TRG
BEFORE UPDATE ON FIDE_TICKET_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO FACTURACION */
CREATE OR REPLACE TRIGGER FIDE_MONEDA_TRG
BEFORE INSERT ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_MONEDA_TRG
BEFORE UPDATE ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_TRG
BEFORE INSERT ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_TRG
BEFORE UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACT_TRG
BEFORE INSERT ON FIDE_VENTA_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACT_TRG
BEFORE UPDATE ON FIDE_VENTA_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TICKET_FACT_TRG
BEFORE INSERT ON FIDE_TICKET_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TICKET_FACT_TRG
BEFORE UPDATE ON FIDE_TICKET_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAGO_PAYPAL_TRG
BEFORE INSERT ON FIDE_PAGO_PAYPAL_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAGO_PAYPAL_TRG
BEFORE UPDATE ON FIDE_PAGO_PAYPAL_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO MUSICA */
CREATE OR REPLACE TRIGGER FIDE_SEASON_TRG
BEFORE INSERT ON FIDE_SEASON_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_SEASON_TRG
BEFORE UPDATE ON FIDE_SEASON_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_SEASON_SET_TRG
BEFORE INSERT ON FIDE_SEASON_SET_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_SEASON_SET_TRG
BEFORE UPDATE ON FIDE_SEASON_SET_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO REDES SOCIALES */
CREATE OR REPLACE TRIGGER FIDE_RED_SOCIAL_TRG
BEFORE INSERT ON FIDE_RED_SOCIAL_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_RED_SOCIAL_TRG
BEFORE UPDATE ON FIDE_RED_SOCIAL_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CTA_RED_SOC_TRG
BEFORE INSERT ON FIDE_CUENTA_RED_SOCIAL_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CTA_RED_SOC_TRG
BEFORE UPDATE ON FIDE_CUENTA_RED_SOCIAL_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

/* MODULO CARRITO DE COMPRAS */
CREATE OR REPLACE TRIGGER FIDE_CARRITO_TRG
BEFORE INSERT ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CARRITO_TRG
BEFORE UPDATE ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CARRITO_ITEM_TRG
BEFORE INSERT ON FIDE_CARRITO_ITEM_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSDATE;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.CREADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CARRITO_ITEM_TRG
BEFORE UPDATE ON FIDE_CARRITO_ITEM_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := :OLD.FECHA_CREACION;
    :NEW.CREADO_POR := :OLD.CREADO_POR;
    :NEW.FECHA_MODIFICACION := SYSDATE;
    :NEW.MODIFICADO_POR := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :NEW.ACCION := 'UPDATE';
END;
/
